spring.config.import=optional:file:.env[.properties]

spring.application.name=TeraMartApp
server.port=8080

# DB configs
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

spring.security.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# JWT vars
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


# Enable CORS for specific endpoints
spring.web.cors.allowed-origin-patterns=http://localhost:5173
spring.web.cors.exposed-headers=* 
spring.web.cors.max-age=36000
spring.web.cors.allowed-origins=http://localhost:5173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=Content-Type,Authorization 
spring.web.cors.allow-credentials=true

# Razorpay keys
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}
